version: "3.2"
services:
  web:
    image: kloktig/api
    build:
      context: .
      dockerfile: api.dockerfile
    ports:
      - "30000:30000"
    environment:
      NODE_ENV : docker
    volumes:
      - ./src:/usr/src/app
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /swagger/swagger.json

    volumes:
      - type: bind
        source: ./src/api/dist/
        target: /swagger